project/portal/apps/accounts/urls.py
"""
.. module:: portal.apps.accounts.urls
   :synopsis: Accounts URLs
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from portal.apps.accounts.views import (IndexView, LoginView,
                                        LogoutView, RegisterView)
from portal.apps.accounts import views

urlpatterns = [
    url(r'^login/?', LoginView.as_view(), name='login'),
    url(r'^logout/?', LogoutView.as_view(), name='logout'),
    # url(r'^register/?', RegisterView.as_view(), name='register'),
    url(r'^register/?', views.register, name='register'),
    url(r'^', IndexView.as_view(), name='index'),
]

project/portal/apps/auth/urls.py
"""
.. module:: portal.apps.auth.urls
   :synopsis: Auth URls
"""
# from django.conf import settings
from django.conf.urls import include, url
from django.core.urlresolvers import reverse
# from django.conf.urls.i18n import i18n_patterns
# from django.conf.urls.static import static
# from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from portal.apps.auth import views

urlpatterns = [
    url(r'^$', views.login_options, name='login'),
    url(r'^logged-out/$', views.logged_out, name='logout'),
    url(r'^agave/$', views.agave_oauth, name='agave_oauth'),
    url(r'^agave/callback/$', views.agave_oauth_callback, name='agave_oauth_callback'),
    url(r'^agave/session-error/$', views.agave_session_error, name='agave_session_error'),
]


def menu_items(**kwargs):
    if 'type' in kwargs and kwargs['type'] == 'account':
        return [
            {
                'label': _('Login'),
                'url': reverse('login'),
                'children': [],
                'visible': False
            },
            {
                'label': _('Login'),
                'url': reverse('designsafe_auth:login'),
                'children': [],
                'visible': False
            },
            {
                'label': _('Agave'),
                'url': reverse('designsafe_auth:agave_session_error'),
                'children': [],
                'visible': False
            }
        ]

project/portal/apps/data_depot/urls.py
"""Date Depot Urls
"""
from django.conf.urls import url
from portal.apps.data_depot import views

urlpatterns = [
    url(r'^', views.DataDepotView.as_view(), name="data_depot"),
]

project/portal/apps/workspace/urls.py
"""Workspace URLs
"""
from django.conf.urls import url
from portal.apps.workspace import views

urlpatterns = [
    url(r'^', views.WorkspaceView.as_view(), name="workspace"),
]

project/portal/urls.py
"""portal URL Configuration
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
#
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect

from portal.apps.auth.views import login_options as des_login_options
from django.contrib.auth.views import logout as des_logout
from portal.views.views import project_version as des_version
#
from views import views

urlpatterns = [
    # admin.
    url(r'^admin/', admin.site.urls),

    # auth.
    url(r'^accounts/', include('portal.apps.accounts.urls',
                               namespace='portal_accounts')),
    url(r'^register/$', RedirectView.as_view(
        pattern_name='portal_accounts:register', permanent=True), name='register'),
    url(r'^auth/', include('portal.apps.auth.urls',
                           namespace='portal_auth')),
    url(r'^login/$', des_login_options, name='login'),
    url(r'^logout/$', des_logout,
        {'next_page': '/auth/logged-out/'}, name='logout'),

    # apps.
    url(r'^data-depot/', include('portal.apps.data_depot.urls',
                                 namespace='data_depot')),
    url(r'^api/data-depot/', include('portal.apps.data_depot.api.urls',
                                     namespace='data_depot_api')),
    url(r'^workspace/', include('portal.apps.workspace.urls',
                                namespace='workspace')),
    url(r'^api/workspace/', include('portal.apps.workspace.api.urls',
                                    namespace='workspace_api')),
    url(r'^$', views.index, name='index'),

    # version check.
    url(r'^version/', des_version),

    # cms handles everything else.
    url(r'^', include('cms.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/portal/apps/accounts/views.py
"""
Accounts views.
"""
from django.contrib.auth import logout
from django.contrib import messages
from django.views.generic.base import TemplateView, View
from django.shortcuts import redirect, render
from django.conf import settings
from django.http import HttpResponseRedirect

from portal.apps.accounts import forms, integrations

import logging

logger = logging.getLogger(__name__)

# Create your views here.

class IndexView(TemplateView):
    """Main accounts view.
    """
    template_name = 'portal/apps/accounts/index.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return redirect('/accounts/login')

        return super(IndexView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        return context


class LoginView(TemplateView):
    """Login options view
    """
    template_name = 'portal/apps/accounts/login.html'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        return context


class LogoutView(View):
    """Logout view
    """
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(settings.LOGIN_URL)


class RegisterView(TemplateView):
    """Register View
    """
    template_name = 'portal/apps/accounts/register.html'


def register(request):
    if request.user.is_authenticated():
        messages.info(request, 'You are already logged in!')
        return HttpResponseRedirect('designsafe_accounts:index')

    if request.method == 'POST':
        account_form = forms.UserRegistrationForm(request.POST)
        if account_form.is_valid():
            try:
                account_form.save()
                return HttpResponseRedirect(
                    reverse('designsafe_accounts:registration_successful'))
            except Exception as e:
                logger.info('error: {}'.format(e))

                error_type = e.args[1] if len(e.args) > 1 else ''

                if 'DuplicateLoginException' in error_type:
                    err_msg = (
                        'The username you chose has already been taken. Please '
                        'choose another. If you already have an account with TACC, '
                        'please log in using those credentials.')
                    account_form._errors.setdefault('username', [err_msg])
                elif 'DuplicateEmailException' in error_type:
                    err_msg = (
                        'This email is already registered. If you already have an '
                        'account with TACC, please log in using those credentials.')
                    account_form._errors.setdefault('email', [err_msg])
                    err_msg = '%s <a href="%s">Did you forget your password?</a>' % (
                        err_msg,
                        reverse('designsafe_accounts:password_reset'))
                elif 'PasswordInvalidException' in error_type:
                    err_msg = (
                        'The password you provided did not meet the complexity '
                        'requirements.')
                    account_form._errors.setdefault('password', [err_msg])
                else:

                    safe_data = account_form.cleaned_data.copy()
                    safe_data['password'] = safe_data['confirmPassword'] = '********'
                    logger.exception('User Registration Error!', extra=safe_data)
                    err_msg = (
                        'An unexpected error occurred. If this problem persists '
                        'please create a support ticket.')
                messages.error(request, err_msg)
        else:
            messages.error(request, 'There were errors processing your registration. '
                                    'Please see below for details.')
    else:
        account_form = forms.UserRegistrationForm()

    context = {
        'account_form': account_form
    }
    return render(request, 'portal/apps/accounts/register.html', context)


def registration_successful(request):
    return render_to_response('designsafe/apps/accounts/registration_successful.html')

project/portal/apps/data_depot/api/views.py
"""
.. :module:: apps.data_depot.api.views
   :synopsys: Views to handle Data Depot API
"""
from __future__ import unicode_literals, absolute_import
import logging
import json
from django.http import JsonResponse
from django.conf import settings
from portal.apps.data_depot.api import lookups as LookupManager
from portal.views.base import BaseApiView
from portal.exceptions.api import ApiException

#pylint: disable=invalid-name
logger = logging.getLogger(__name__)
METRICS = logging.getLogger('metrics.{}'.format(__name__))
#pylint: enable=invalid-name

def get_manager(request, file_mgr_name):
    fmgr_cls = LookupManager.lookup_manager(file_mgr_name)
    fmgr = fmgr_cls(request)
    if fmgr.requires_auth and not request.user.is_authenticated:
        raise ApiException("Login Required", status=403)
    return fmgr


class ProjectListingView(BaseApiView):
    """ Projects listing view"""
    def get(self, request):

        ac = request.user.agave_oauth.client
        listing  = ac.systems.list(type="STORAGE")
        projects = [s for s in listing if '-projects-' in s.id]
        return JsonResponse({'response': projects})


#TODO: Make this general!
class SystemListingView(BaseApiView):
    """System Listing View"""

    def get(self, request):
        ac = request.user.agave_oauth.client
        listing = ac.systems.list(type="STORAGE")
        community_data_system = settings.AGAVE_COMMUNITY_DATA_SYSTEM
        #mydata_system = "data-tacc-work-{uname}".format(uname=request.user.username)
	mydata_system = settings.AGAVE_STORAGE_SYSTEM
        listing = [
            {
                "systemId": community_data_system,
                "name": "Community Data"
            },
            {
                "systemId": mydata_system,
                "name": "My Data"
            }
        ]
        return JsonResponse({'response': listing})

class ToolbarOptionsView(BaseApiView):

    def get(self, request):
        toolbar_options = settings.TOOLBAR_OPTIONS

        return JsonResponse({'response': toolbar_options})

class FileListingView(BaseApiView):
    """File Listing View"""
    def get(self, request, file_mgr_name, file_id, **kwargs):
        """GET Handles files listing"""

        METRICS.info('File Listing: file_mgr=%s, path=%s', file_mgr_name, file_id,
                     extra={'user': request.user.username,
                            'sessionId': request.session.session_key,
                            'operation': 'File Listing', 'info': ''})
        logger.debug("%s", file_id)
        fmgr = get_manager(request, file_mgr_name)
        #logger.debug("%s", str(fmgr))
        offset = kwargs.get('offset', 0)
        limit = kwargs.get('limit', 100)
        listing = fmgr.listing(file_id, offset=offset, limit=limit, username=request.user.username)
        logger.debug("%s", str(listing))
        return JsonResponse({'response': listing},
                            encoder=fmgr.encoder_cls)

class FileMediaView(BaseApiView):
    """File Media View"""

    ALLOWED_FILE_ACTIONS = ['copy', 'download',
                            'mkdir', 'move', 'rename', 'trash', 'preview']

    def get(self, request, file_mgr_name, file_id, **kwargs):
        """GET

        This method handles file downloads.

        :param request: Django request.
        :param str file_mgr_name: Manager name.
        :param str file_id: Id representation of a file.

        .. note:: We do not serve the files because we assume that
         files live in an external service, e.g. Agave, box, dropbox, etc...
         Usually, the response will contain a link directly to the file.
        """
        METRICS.info('Get File: file_mgr=%s, path=%s', file_mgr_name, file_id)
        fmgr = get_manager(request, file_mgr_name)
        preview = request.GET.get('preview', True)
        resp = fmgr.download(file_id, preview)
        return JsonResponse({'respose': resp},
                            encoder=fmgr.encoder_cls)

    def post(self, request, file_mgr_name, file_id, **kwargs):
        """POST

        This method handles file uploads.

        :param request: Django request.
        :param str file_mgr_name: Manager name.
        :param str file_id: Id representation of a file.

        .. todo:: Implement folder uploads.
        """
        fmgr = get_manager(request, file_mgr_name)
        #fileList = []
        #for fileI in request.FILES['file']:
            #fileList.append(fileI)
        #logger.debug("%s", str(len(fileList)))
        files = request.FILES.getlist('file')
        resp = fmgr.upload(file_id, files)
        #resp = fmgr.upload(file_id, [request.FILES['file']])
        return JsonResponse({'response': resp},
                            encoder=fmgr.encoder_cls)

    def delete(self, request, file_mgr_name, file_id, **kwargs):
        """DELETE"""
        fmgr = get_manager(request, file_mgr_name)
        fmgr.delete(file_id)
        return JsonResponse({'response': 'OK'})

    def put(self, request, file_mgr_name, file_id, **kwargs):
        """PUT

        Most of the file actions are routed through this method.
        The actions allowed are listed in :attr:`ALLAWED_FILE_ACTIONS`.

        .. rubric:: Rationale

        If the action is allowed then a method with the same name will
        be called. This means there will be a few methods in this class
        that map directly on to methods in a File Manager. By separating
        any action into methods read-ability is improved. Mostly because
        these view classes should take care of parse the request body
        correctly and *not* every method in a file manager can have
        the same type of signature.

        """
        fmgr = get_manager(request, file_mgr_name)
        if request.is_ajax():
            req_body = json.loads(request.body)
        else:
            req_body = request.POST.copy()

        action = req_body.get('action')
        operation = None
        if action not in self.ALLOWED_FILE_ACTIONS:
            raise ApiException("Invalid file action")

        try:
            operation = getattr(self, action)
        except AttributeError:
            raise ApiException("Invalid file action.")

        resp = operation(request, req_body, file_id, fmgr)
        return JsonResponse({'response': resp},
                            encoder=fmgr.encoder_cls)

    def copy(self, request, req_body, file_id, fmgr):
        """Copy action

        .. todo:: Take care of copy between systems.
        """
        return fmgr.copy(file_id, req_body.get('path'))

    def download(self, request, req_body, file_id, fmgr):
        """Download action"""
        return fmgr.download(file_id,preview=False)

    def mkdir(self, request, req_body, file_id, fmgr):
        """Mkdir action"""
        return fmgr.mkdir(file_id, req_body['name'])

    def move(self, request, req_body, file_id, fmgr):
        """Move action"""
        return fmgr.move(file_id, req_body['path'])

    def rename(self, request, req_body, file_id, fmgr):
        """Rename action"""
        return fmgr.rename(file_id, req_body['name'])

    def trash(self, request, req_body, file_id, fmgr):
        """Trash action"""
        return fmgr.trash(file_id)
    
    def preview(self, request, req_body, file_id, fmgr):
        # I added this
        """Preview action"""
        return fmgr.download(file_id, preview=True)

class FilePemsView(BaseApiView):
    """View to handle permissions operations"""
    def get(self, request, file_mgr_name, file_id, **kwargs):
        """GET"""
        METRICS.info('file_mgr_name=%s, file_id=%s', file_mgr_name, file_id,
                     extra=
                     {
                         'user': request.user.username,
                         'sessionId': request.session.session_key,
                         'operation': 'pems listing',
                         'info': ''
                     })
        fmgr = get_manager(request, file_mgr_name)
        pems = fmgr.pems(file_id, request.user.username)
        return JsonResponse({'response': pems},
                            encoder=fmgr.encoder_cls)

    def post(self, request, file_mgr_name, file_id, **kwargs):
        """POST -- I added this"""

        fmgr = get_manager(request, file_mgr_name)
        #pems = fmgr.pems(file_id, request.user.username)
        #logger.debug("%s", str(request.user))
        #resp = fmgr.share(file_id)

	if request.is_ajax():
            req_body = json.loads(request.body)
        else:
            req_body = request.POST.copy()
	logger.debug("%s", str(req_body))
	
	for myValue in req_body.iterkeys():
		logger.debug("%s", str(myValue))
	
        logger.debug("%s", str(type(req_body)))
	resp = fmgr.update_pems(file_id, [req_body]) # will only handle one set of permissions
        return JsonResponse({'response': resp},
                            encoder=fmgr.encoder_cls)

project/portal/templates/includes/analytics.html
{% if GOOGLE_ANALYTICS_PROPERTY_ID %}
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', '{{ GOOGLE_ANALYTICS_PROPERTY_ID }}', 'auto');
ga('send', 'pageview');
</script>
{% endif %}

project/portal/templates/includes/cms_menu.html
{% load i18n menu_tags cache %}

{% for child in children %}
<li class="{% if child.ancestor or child.selected or request.get_full_path == child.url %}active{% endif %} {% if child.children %}dropdown{% endif %} {{child.attr.class}}">
    {% if child.children %}
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ child.get_menu_title | safe }} <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <!--
        <li {%if child.selected %}class="active"{% endif %}>
          <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title | safe }}</span></a>
        </li>
        -->
        {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
      </ul>
    {% else %}
      <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title | safe }}</span></a>
    {% endif %}
</li>
{% endfor %}

project/portal/templates/includes/footer.html
{% load staticfiles cms_tags %}
<footer class="container-fluid">
  <hr>
  {% static_placeholder 'site_footer' site or %}
  <p class="text-center">
	SD2E Portal
  </p>
  {% endstatic_placeholder %}
</footer>

project/portal/templates/includes/global_nav.html
<li><a href="/">UT-Portal Home</a></li>
<li role="separator" class="divider"></li>
<li><a href="/data-depot/"> Data Depot </a></li>
<li><a href="/workspace/"> Workspace </a></li>
<!--
<li><a href="/community/">Community</a></li>
<li role="separator" class="divider"></li>
<li><a href="/account/">My Account</a></li>
<li><a href="/help/">Help</a></li>
<li><a href="/contact/">Contact</a></li>
<li><a href="/about/">About</a></li>
-->

project/portal/templates/includes/header.html
{% load staticfiles %}
{% load static %}
<header class="container-fluid site-banner">
  <div class="pull-left">
    <a class="logo" href="/">
      <img alt="UT-PORTAL" src="{% static 'portal/img/logo.png' %}" height="40"/>
    </a>
  </div>

  <div class="site-banner-right">
    <div class="user-menu">
      {% if user.is_authenticated %}
        <!--
        <span>
          Welcome, {{ user.first_name }}!
          {% if not request.user.agave_oauth %}
            &nbsp;
            <a class="text-danger" title="API Session Not Available. Click for details." href="{% url 'portal_auth:agave_session_error' %}"><i class="fa fa-exclamation-triangle"></i><span class="sr-only">API Session Not Available. Click for details.</span></a>
          {% endif %}
        </span>-->

        <div class="btn-group pull-right">
          <a href="{% url 'portal_accounts:index' %}" class="btn btn-link-alt">My account</a>
          <button type="button" class="btn default dropdown-toggle"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <!--
            <li><a href="{% url 'portal_accounts:logout' %}">Log out</a></li>
            -->
            <li><a href="{% url 'portal_accounts:logout' %}">Log out</a></li>
            {% if user.is_impersonate %}
              <li><a href="{% url 'impersonate-stop' %}">Stop impersonating {{user}}</a></li>
            {% endif %}
          </ul>
        </div>

      {% else %}
      <div class="btn-group">
        <a href="{% url 'portal_accounts:login' %}" class="btn btn-link-alt">Log in</a>
        <a href="{% url 'portal_accounts:register' %}" class="btn btn-link-alt">Register</a>
      </div>
      {% endif %}
    </div>

  </div>

</header>

project/portal/templates/includes/messages.html
{% if messages %}
  <div class="messages">
    <div class="container">
      {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <p>{{ message|safe }}</p>
      </div>
      {% endfor %}
    </div>
  </div>
{% endif %}

project/portal/templates/includes/navigation.html
{% load menu_tags cms_tags staticfiles %}
<nav class="navbar navbar-default navbar-ds">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-left"><img src="{% static 'portal/img/logo.png'%}" height="40px" style="padding-right:10px"></a>
      <ul class="nav navbar-nav hidden-xs">
        {% if user.is_authenticated %}
        <li class="dropdown">

            <a class="dropdown-toggle"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

              <i class="fa fa-wrench"></i> Research Workbench
              <span class="caret"></span>
              <span class="sr-only">Toggle Dropdown</span>

            </a>
            <ul class="dropdown-menu">
        <li>
          <a href="{% url 'data_depot:data_depot' %}">
            <i class="fa fa-database"> </i> Data Depot
          </a>
        </li>
        <li>
          <a href="{% url 'workspace:workspace' %}">
            <i class="fa fa-rocket"> </i> Workspace
          </a>
        </li>
            </ul>
        </li>


        {% endif %}
        <li>
          <a href="{% url 'workspace:workspace' %}">
            <i class="fa fa-info"> </i> About
          </a>
        </li>
        <li>
          <a href="{% url 'workspace:workspace' %}">
            <i class="fa fa-question"> </i> Help
          </a>
        </li>
      </ul>
      {% if section_root %}
        <a class="navbar-brand">{{section_root.title}}</a>
      {% endif %}
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navigation" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-navigation">
      <ul class="nav navbar-nav">
         {% show_menu 1 2 100 100 "includes/cms_menu.html" %}
      </ul>
      <ul class="nav navbar-nav global-nav hidden-sm hidden-md hidden-lg">
        {% include 'includes/global_nav.html' %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <!--
          <span>
            Welcome, {{ user.first_name }}!
            {% if not request.user.agave_oauth %}
              &nbsp;
              <a class="text-danger" title="API Session Not Available. Click for details." href="{% url 'portal_auth:agave_session_error' %}"><i class="fa fa-exclamation-triangle"></i><span class="sr-only">API Session Not Available. Click for details.</span></a>
            {% endif %}
          </span>-->

          <li class="dropdown">

            <a class="dropdown-toggle"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

              <i class="fa fa-user-circle fa-lg"></i>
              <span class="caret"></span>
              <span class="sr-only">Toggle Dropdown</span>

            </a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'portal_accounts:index' %}">My account</a></li>
              <li><a href="{% url 'portal_accounts:logout' %}">Log out</a></li>
              {% if user.is_impersonate %}
                <li><a href="{% url 'impersonate-stop' %}">Stop impersonating {{user}}</a></li>
              {% endif %}
            </ul>

          {% else %}
            <div class="btn-group">
              <a href="{% url 'portal_accounts:login' %}" class="btn btn-link-alt">Log in</a>
              <a href="{% url 'portal_accounts:register' %}" class="btn btn-link-alt">Register</a>
            </div>
          {% endif %}
        </div>
      </ul>
    </div><!-- /.navbar-collapse -->


</nav>