project/portal/apps/accounts/urls.py
"""
.. module:: portal.apps.accounts.urls
   :synopsis: Accounts URLs
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from portal.apps.accounts.views import (IndexView, LoginView,
                                        LogoutView, RegisterView)
from portal.apps.accounts import views

urlpatterns = [
    url(r'^login/?', LoginView.as_view(), name='login'),
    url(r'^logout/?', LogoutView.as_view(), name='logout'),
    # url(r'^register/?', RegisterView.as_view(), name='register'),
    url(r'^register/?', views.register, name='register'),
    url(r'^', IndexView.as_view(), name='index'),
]

project/portal/apps/auth/urls.py
"""
.. module:: portal.apps.auth.urls
   :synopsis: Auth URls
"""
# from django.conf import settings
from django.conf.urls import include, url
from django.core.urlresolvers import reverse
# from django.conf.urls.i18n import i18n_patterns
# from django.conf.urls.static import static
# from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from portal.apps.auth import views

urlpatterns = [
    url(r'^$', views.login_options, name='login'),
    url(r'^logged-out/$', views.logged_out, name='logout'),
    url(r'^agave/$', views.agave_oauth, name='agave_oauth'),
    url(r'^agave/callback/$', views.agave_oauth_callback, name='agave_oauth_callback'),
    url(r'^agave/session-error/$', views.agave_session_error, name='agave_session_error'),
]


def menu_items(**kwargs):
    if 'type' in kwargs and kwargs['type'] == 'account':
        return [
            {
                'label': _('Login'),
                'url': reverse('login'),
                'children': [],
                'visible': False
            },
            {
                'label': _('Login'),
                'url': reverse('designsafe_auth:login'),
                'children': [],
                'visible': False
            },
            {
                'label': _('Agave'),
                'url': reverse('designsafe_auth:agave_session_error'),
                'children': [],
                'visible': False
            }
        ]

project/portal/urls.py
"""portal URL Configuration
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
#
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect

from portal.apps.auth.views import login_options as des_login_options
from django.contrib.auth.views import logout as des_logout
from portal.views.views import project_version as des_version
#
from views import views

urlpatterns = [
    # admin.
    url(r'^admin/', admin.site.urls),

    # auth.
    url(r'^accounts/', include('portal.apps.accounts.urls',
                               namespace='portal_accounts')),
    url(r'^register/$', RedirectView.as_view(
        pattern_name='portal_accounts:register', permanent=True), name='register'),
    url(r'^auth/', include('portal.apps.auth.urls',
                           namespace='portal_auth')),
    url(r'^login/$', des_login_options, name='login'),
    url(r'^logout/$', des_logout,
        {'next_page': '/auth/logged-out/'}, name='logout'),

    # apps.
    url(r'^data-depot/', include('portal.apps.data_depot.urls',
                                 namespace='data_depot')),
    url(r'^api/data-depot/', include('portal.apps.data_depot.api.urls',
                                     namespace='data_depot_api')),
    url(r'^workspace/', include('portal.apps.workspace.urls',
                                namespace='workspace')),
    url(r'^api/workspace/', include('portal.apps.workspace.api.urls',
                                    namespace='workspace_api')),
    url(r'^$', views.index, name='index'),

    # version check.
    url(r'^version/', des_version),

    # cms handles everything else.
    url(r'^', include('cms.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/portal/apps/accounts/models.py
from __future__ import unicode_literals

import logging
from django.core.mail import send_mail
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.


#pylint: disable=invalid-name
logger = logging.getLogger(__name__)
#pylint: enable=invalid-name


class PortalProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile')
    ethnicity = models.CharField(max_length=255)
    gender = models.CharField(max_length=255)

    def send_mail(self, subject, body=None):
        send_mail(subject,
                  body,
                  settings.DEFAULT_FROM_EMAIL,
                  [self.user.email],
                  html_message=body)


class NotificationPreferences(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                related_name='notification_preferences')
    announcements = models.BooleanField(
        default=True,
        verbose_name=_('Receive occasional announcements from DesignSafe'))

    class Meta:
        permissions = (
            ('view_notification_subscribers', 'Can view list of users subscribed to a '
                                              'notification type'),
        )


class PortalProfileNHInterests(models.Model):
    description = models.CharField(max_length=300)

    def __unicode__(self):
        return self.description


class PortalProfileResearchActivities(models.Model):
    description = models.CharField(max_length=300)

    def __unicode__(self):
        return self.description

project/portal/apps/accounts/views.py
"""
Accounts views.
"""
from django.contrib.auth import logout
from django.contrib import messages
from django.views.generic.base import TemplateView, View
from django.shortcuts import redirect, render
from django.conf import settings
from django.http import HttpResponseRedirect

from portal.apps.accounts import forms, integrations

import logging

logger = logging.getLogger(__name__)

# Create your views here.

class IndexView(TemplateView):
    """Main accounts view.
    """
    template_name = 'portal/apps/accounts/index.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return redirect('/accounts/login')

        return super(IndexView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        return context


class LoginView(TemplateView):
    """Login options view
    """
    template_name = 'portal/apps/accounts/login.html'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        return context


class LogoutView(View):
    """Logout view
    """
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(settings.LOGIN_URL)


class RegisterView(TemplateView):
    """Register View
    """
    template_name = 'portal/apps/accounts/register.html'


def register(request):
    if request.user.is_authenticated():
        messages.info(request, 'You are already logged in!')
        return HttpResponseRedirect('designsafe_accounts:index')

    if request.method == 'POST':
        account_form = forms.UserRegistrationForm(request.POST)
        if account_form.is_valid():
            try:
                account_form.save()
                return HttpResponseRedirect(
                    reverse('designsafe_accounts:registration_successful'))
            except Exception as e:
                logger.info('error: {}'.format(e))

                error_type = e.args[1] if len(e.args) > 1 else ''

                if 'DuplicateLoginException' in error_type:
                    err_msg = (
                        'The username you chose has already been taken. Please '
                        'choose another. If you already have an account with TACC, '
                        'please log in using those credentials.')
                    account_form._errors.setdefault('username', [err_msg])
                elif 'DuplicateEmailException' in error_type:
                    err_msg = (
                        'This email is already registered. If you already have an '
                        'account with TACC, please log in using those credentials.')
                    account_form._errors.setdefault('email', [err_msg])
                    err_msg = '%s <a href="%s">Did you forget your password?</a>' % (
                        err_msg,
                        reverse('designsafe_accounts:password_reset'))
                elif 'PasswordInvalidException' in error_type:
                    err_msg = (
                        'The password you provided did not meet the complexity '
                        'requirements.')
                    account_form._errors.setdefault('password', [err_msg])
                else:

                    safe_data = account_form.cleaned_data.copy()
                    safe_data['password'] = safe_data['confirmPassword'] = '********'
                    logger.exception('User Registration Error!', extra=safe_data)
                    err_msg = (
                        'An unexpected error occurred. If this problem persists '
                        'please create a support ticket.')
                messages.error(request, err_msg)
        else:
            messages.error(request, 'There were errors processing your registration. '
                                    'Please see below for details.')
    else:
        account_form = forms.UserRegistrationForm()

    context = {
        'account_form': account_form
    }
    return render(request, 'portal/apps/accounts/register.html', context)


def registration_successful(request):
    return render_to_response('designsafe/apps/accounts/registration_successful.html')

project/portal/apps/accounts/templates/portal/apps/accounts/index.html
{% extends "base.html" %}
{% load sekizai_tags staticfiles %}

{% block title %} Accounts {% endblock %}

project/portal/apps/accounts/templates/portal/apps/accounts/login.html
{% extends "base.html" %}
{% load sekizai_tags staticfiles %}

{% block title %} Login {% endblock %}

{% block content %}

<div class="container">
  <h1 class="headline headline-community">SD2E Portal Login</h1>
  <p class="lead">
    Choose an option below to log into the SD2E Portal.
  </p>

  <div class="row">
    <div class="col-sm-6">
      {% if message %}
      <div class="alert alert-{{message.class}}">
        <p>{{message.text}}</p>
      </div>
      {% endif %}
      <div class="login-option-block">
        <p>
          <a href="{% url 'portal_auth:agave_oauth' %}?{{ request.META.QUERY_STRING }}" class="btn btn-lg btn-primary img-responsive">
            <img class="provider-logo img-responsive" style="width:100% \9;" alt="TACC" title="Log in with TACC" src="{% static 'images/portal/logos/tacc.svg'%}">
          </a>
        </p>

        <p>
          <a href="{% url 'portal_auth:agave_oauth' %}?{{ request.META.QUERY_STRING }}">Log in using your TACC Account.</a>
        </p>
        <a href="{% url 'portal_accounts:register' %}?{{ request.META.QUERY_STRING }}">Register for a TACC account</a>
        &bull;
        <a href="https://www.tacc.utexas.edu">TACC Website</a>
      </div>
  </div>

</div>

{% endblock %}

project/portal/apps/accounts/templates/portal/apps/accounts/register.html
{% extends "base.html" %}
{% load bootstrap3 sekizai_tags staticfiles %}
{% block title %} Registration {% endblock %}
{% block content %}
  <div class="container">
    <h1 class="headline headline-research">Register an Account</h1>

    <div class="row">
      <div class="col-md-5 col-md-push-7">
        <div class="callout callout-default">
          <p class="text-center">
            <img style="max-width:300px" alt="TACC" src="{% static 'images/tacc-logo-outline.svg'%}">
          </p>
          <h3>
            Already have an Account? <a href="{% url 'portal_auth:login' %}">Log in.</a>
          </h3>
          <p>
            If you already have a TACC account, simply
            <a href="{% url 'portal_auth:agave_oauth' %}">log in</a> with your TACC username and password to access SD2E.
          </p>
          <p>
            You may have a TACC account if you have used XSEDE or TeraGrid in the past and had an allocation on a TACC resource.
          </p>
        </div>
      </div>

      <div class="col-md-7 col-md-pull-5">
        <p class="lead">
          SD2E uses the TACC Identity Service. To use SD2E you need to
          register for a TACC Account. With a TACC Account you will be able to access
          SD2E as well as additional services provided by TACC. See the
          <a href="https://www.tacc.utexas.edu" target="_blank">TACC Website</a> for more
          information.
        </p>
        <form method="post" action="">
          {% csrf_token %}
          {% bootstrap_form account_form %}
          <button class="btn btn-primary" type="submit">Register Account</button>
          <a class="btn btn-link" href="/">Cancel</a>
          <a class="btn btn-link" href="{% url 'login' %}">Already have an account? Log in.</a>
        </form>
      </div>
    </div>

  </div>
  {% addtoblock 'js' %}
    <script type="text/javascript" src="{% static 'portal/apps/accounts/js/institution_departments.js' %}"></script>
    <script type="text/javascript" src="{% static 'portal/apps/accounts/js/new_institution.js' %}"></script>
  {% endaddtoblock %}
{% endblock %}